[package]
name = "log_shark"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "2.0"
clap = { version = "4.0", features = ["derive"] }
regex = "1.10"
chrono = "0.4"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
rayon = "1.8"
